site_name: The NeoFanDoc
site_url: https://neofandoc.readthedocs.io/en/latest/
theme:
  name: rtd-dropdown
extra_css:
  - font_rules.css
nav:
  - Home: index.md
  - Warming up:
      - setup/starter.md
      - Set up Java: setup/setup_java.md
      - Set up an IDE: setup/setup_idea.md
markdown_extensions:
  - admonition