site_name: The NeoFanDoc
site_url: https://neofandoc.readthedocs.io/en/latest/
theme:
  name: null
  custom_dir: 'rtd_dropdown/'
extra_css:
  - font_rules.css
nav:
  - Home: index.md
  - Warming up:
      - setup/starter.md
      - Setup Java: setup/setup.md
markdown_extensions:
  - admonition